connector.name=iceberg
iceberg.catalog.type=rest
iceberg.rest-catalog.uri=http://nessie:19120/iceberg/main
iceberg.rest-catalog.warehouse=s3://silver/
iceberg.rest-catalog.security=NONE

fs.native-s3.enabled=true
s3.endpoint=http://storage:9000
s3.region=us-east-1
s3.path-style-access=true
s3.aws-access-key=root
s3.aws-secret-key=password
